sonar.projectKey=flask-taskmanager
sonar.projectName=Flask Task Manager
sonar.projectVersion=1.0
sonar.sources=app
sonar.tests=tests
sonar.language=py
sonar.python.coverage.reportPaths=coverage.xml
sonar.exclusions=**/__pycache__/**,**/*.pyc
sonar.host.url=http://localhost:9000